### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by ginkgomzd**
Hope you like these edits. Feel free to change as you see fit before merging.

### CODE REVIEW

**Comment by wmortada** [comment]
Looks good to me (other than a typo I spotted).

**Comment by ginkgomzd** [comment]
I spied a missing period. Is there another typo?

**Comment by wmortada** [comment]
Missing 'o' in 'compose'. See review comments.

**Comment by ginkgomzd** [comment]
> Missing 'o' in 'compose'. See review comments.

I thought it was the mobile app I was using... but I'm on desktop now and don't see a review.

**Comment by michaelmcandrew** [comment]
looks good to me. happy to merge with or without the o :)

**Comment by wmortada** [comment]
Sorry, I was using the app on my phone and didn't realise that I needed to click send for the comment to be added. Hopefully, you can see it now!

**Comment by ginkgomzd** [comment]
Now with more punctuation and vowels!

I think this is ready.

Cheers

**Comment by michaelmcandrew** [comment]
thanks!

**Pull request merged**
